### ISSUE TITLE
PercentageValue error and fix  next error 

### ISSUE THREAD

**Issue by wing158** [lin-jinwei/OneTo3D#1]
Traceback (most recent call last):
  File "/root/OneTo3D/dg1.py", line 915, in <module>
    gui.train(opt.iters)
  File "/root/OneTo3D/dg1.py", line 896, in train
    self.save_model(mode='geo+tex')
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/OneTo3D/dg1.py", line 418, in save_model
    mesh = self.renderer.gaussians.extract_mesh(path, self.opt.density_thresh)
  File "/root/OneTo3D/gs_renderer.py", line 309, in extract_mesh
    vertices, triangles = clean_mesh(vertices, triangles, remesh=True, remesh_size=0.015)
  File "/root/OneTo3D/mesh_utils.py", line 115, in clean_mesh
    threshold=pml.PercentageValue(v_pct)
AttributeError: module 'pymeshlab' has no attribute 'PercentageValue'

and fix:
  if v_pct > 0:
        **pml.PercentageValue = pml.Percentage
        pml.PureValue = pml.AbsoluteValue**   
        ms.meshing_merge_close_vertices(
            threshold=pml.PercentageValue(v_pct)
        )  # 1/10000 of bounding box diagonal

 error:
=====================================
root@cd410bb68628:~/OneTo3D# python dg1.py --config configs/image-2.yaml input=data/people_rgba.png save_path=data/people_rgba/people_rgba.png
[INFO] load image from data/people_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Keyword arguments {'trust_remote_code': True} are not expected by Zero123Pipeline and will be ignored.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 13.32it/s]
[INFO] loaded zero123!
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:48<00:00, 10.37it/s]
[INFO] save model to ouputModels/data/people_rgba/people_rgba_model.ply.
/usr/local/lib/python3.9/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0 ∈ [0.0, 47.94729995727539] μ = 0.24909809231758118 σ = 1.9603266716003418
[INFO] mesh cleaning: (18276, 3) --> (11392, 3), (36548, 3) --> (22780, 3)
[INFO] marching cubes result: torch.Size([11392, 3]) (-0.6866886019706726-0.7197567224502563), torch.Size([22780, 3])
[INFO] unwrap uv...
[F glutil.cpp:338] eglInitialize() failed

**Comment by wing158** [comment]
fix

**Comment by wing158** [comment]
fix
